server:
  port: 8081
spring:
  application:
    name: client
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:quant
    username: tushare
    password: tushare
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    #    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
feign:
  client:
    config:
      default:
        loggerLevel: full
tushare:
  token: 38625237adbb054f362501dd9e8ebaa68e8406ac316e6c792ec41600
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    org.p8499.quant.tushare.feignClient.*: DEBUG