server:
  port: 9002
spring:
  application:
    name: tushare
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:quant2
    username: tushare
    password: tushare
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    #    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

tushare:
  token: 38625237adbb054f362501dd9e8ebaa68e8406ac316e6c792ec41600

analysis:
  persistent:
    url: http://localhost:88/analysis/persistent

feign:
  client:
    config:
      default:
        loggerLevel: full
        readTimeout: 600000

logging:
  level:
    org.hibernate.SQL: off
    org.p8499.quant.tushare.feignClient.*: info
    org.p8499.quant.tushare.service.*: info