server:
  port: 9000
eureka:
  instance:
    hostname: 192.168.101.11
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/