server:
  port: 9001
spring:
  application:
    name: analysis
  datasource:
    url: jdbc:oracle:thin:@192.168.101.11:1521:quant
    username: analysis
    password: analysis
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    #    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  redis:
    host: 192.168.101.11
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: 192.168.101.11
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.101.11:9000/eureka/
logging:
  level:
    org.hibernate.SQL: off