server:
  port: 9001
spring:
  application:
    name: analysis
  datasource:
    url: jdbc:oracle:thin:@192.168.101.11:1521:quant
    username: analysis
    password: analysis
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
  jpa:
    database: oracle
    #    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  redis:
    host: 192.168.101.11
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: 192.168.101.11
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
  mail:
    host: smtp.126.com
    port: 465
    username: p8499@126.com
    password: Sou`12
    default-encoding: UTF-8
    # Other properties
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # TLS , port 587
          starttls:
            enable: true
            required: true
          # SSL, post 465
          ssl:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.101.11:9000/eureka/
logging:
  level:
    org.hibernate.SQL: off
    org.p8499.quant.analysis.service.*: info