server:
  port: 9001
spring:
  application:
    name: analysis
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:quant2
    username: analysis
    password: analysis
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
  jpa:
    database: oracle
    #    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
logging:
  level:
    org.hibernate.SQL: off
    org.p8499.quant.analysis.service.*: debug